name: Fake Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production  # ✅ Required for GitHub to detect deployment
    steps:
      - name: Fake Deployment Step
        run: echo "Deploying to production..."
